// src/components/attestation/NouvelleDemandeModal.tsx
import { useState, useMemo } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EmployeeAvatar } from "./EmployeeAvatar";
import { TYPES_ATTESTATION, EMPLOYEES, CURRENT_USER_ID, searchEmployees, getEmployee } from "@/lib/attestation-logic";
import type { Employee } from "@/lib/attestation-logic";
import { User, Users, Search } from "lucide-react";

interface NouvelleDemandeModalProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (employeeId: string, type: string, motif: string) => void;
}

export function NouvelleDemandeModal({ open, onClose, onSubmit }: NouvelleDemandeModalProps) {
  const [mode, setMode] = useState<"choice" | "form">("choice");
  const [forSelf, setForSelf] = useState(true);
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);
  const [empSearch, setEmpSearch] = useState("");
  const [type, setType] = useState("");
  const [motif, setMotif] = useState("");

  const filteredEmployees = useMemo(() => {
    if (!empSearch) return EMPLOYEES.filter((e) => e.id !== CURRENT_USER_ID);
    return searchEmployees(empSearch).filter((e) => e.id !== CURRENT_USER_ID);
  }, [empSearch]);

  const reset = () => {
    setMode("choice");
    setForSelf(true);
    setSelectedEmployee(null);
    setEmpSearch("");
    setType("");
    setMotif("");
  };

  const handleClose = () => {
    reset();
    onClose();
  };

  const handleSubmit = () => {
    const empId = forSelf ? CURRENT_USER_ID : selectedEmployee?.id;
    if (!empId || !type) return;
    onSubmit(empId, type, motif);
    handleClose();
  };

  const chooseMode = (self: boolean) => {
    setForSelf(self);
    if (self) {
      setSelectedEmployee(getEmployee(CURRENT_USER_ID) || null);
    }
    setMode("form");
  };

  return (
    <Dialog open={open} onOpenChange={(o) => !o && handleClose()}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Nouvelle Demande</DialogTitle>
        </DialogHeader>

        {mode === "choice" && (
          <div className="grid grid-cols-2 gap-4 py-4">
            <button
              onClick={() => chooseMode(true)}
              className="flex flex-col items-center gap-3 p-6 rounded-lg border-2 border-border hover:border-primary hover:bg-muted/50 transition-all"
            >
              <User className="h-8 w-8 text-primary" />
              <span className="font-medium">Pour moi</span>
            </button>
            <button
              onClick={() => chooseMode(false)}
              className="flex flex-col items-center gap-3 p-6 rounded-lg border-2 border-border hover:border-primary hover:bg-muted/50 transition-all"
            >
              <Users className="h-8 w-8 text-primary" />
              <span className="font-medium">Pour un employé</span>
            </button>
          </div>
        )}

        {mode === "form" && (
          <div className="space-y-4 py-2">
            {!forSelf && !selectedEmployee && (
              <div className="space-y-3">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Rechercher un employé..."
                    value={empSearch}
                    onChange={(e) => setEmpSearch(e.target.value)}
                    className="pl-9"
                    autoFocus
                  />
                </div>
                <div className="max-h-48 overflow-y-auto rounded-lg border divide-y">
                  {filteredEmployees.map((emp) => (
                    <button
                      key={emp.id}
                      onClick={() => setSelectedEmployee(emp)}
                      className="w-full flex items-center gap-3 p-3 hover:bg-muted/50 transition-colors text-left"
                    >
                      <EmployeeAvatar initials={emp.avatar} size="sm" />
                      <div>
                        <p className="text-sm font-medium">{emp.prenom} {emp.nom}</p>
                        <p className="text-xs text-muted-foreground">{emp.poste}</p>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {(forSelf || selectedEmployee) && (
              <>
                {/* Profile card */}
                <div className="flex items-center gap-4 p-4 rounded-lg bg-muted/50 border">
                  <EmployeeAvatar initials={(forSelf ? getEmployee(CURRENT_USER_ID) : selectedEmployee)?.avatar || "?"} size="lg" />
                  <div>
                    <p className="font-semibold">
                      {(() => {
                        const e = forSelf ? getEmployee(CURRENT_USER_ID) : selectedEmployee;
                        return e ? `${e.prenom} ${e.nom}` : "";
                      })()}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      {(forSelf ? getEmployee(CURRENT_USER_ID) : selectedEmployee)?.poste}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {(forSelf ? getEmployee(CURRENT_USER_ID) : selectedEmployee)?.departement}
                    </p>
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium">Type d'attestation *</label>
                  <Select value={type} onValueChange={setType}>
                    <SelectTrigger>
                      <SelectValue placeholder="Sélectionner un type" />
                    </SelectTrigger>
                    <SelectContent>
                      {TYPES_ATTESTATION.map((t) => (
                        <SelectItem key={t} value={t}>{t}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium">Motif <span className="text-muted-foreground">(facultatif)</span></label>
                  <Textarea
                    placeholder="Précisez le motif de votre demande..."
                    value={motif}
                    onChange={(e) => setMotif(e.target.value)}
                    rows={3}
                  />
                </div>

                <div className="flex justify-end gap-3 pt-2">
                  <Button variant="outline" onClick={handleClose}>Annuler</Button>
                  <Button onClick={handleSubmit} disabled={!type}>Soumettre</Button>
                </div>
              </>
            )}

            {!forSelf && !selectedEmployee && (
              <div className="flex justify-start">
                <Button variant="ghost" onClick={() => setMode("choice")}>← Retour</Button>
              </div>
            )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

// src/components/attestation/NouvelleDemandeModal.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import EmployeeAvatar from "./EmployeeAvatar.vue";
import { TYPES_ATTESTATION, EMPLOYEES, CURRENT_USER_ID, searchEmployees, getEmployee } from "@/lib/attestation-logic";
import type { Employee } from "@/lib/attestation-logic";
import { User, Users, Search } from "lucide-vue-next";

interface NouvelleDemandeModalProps {
  open: boolean;
}

const props = defineProps<NouvelleDemandeModalProps>();
const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'submit', employeeId: string, type: string, motif: string): void;
}>();

const mode = ref<"choice" | "form">("choice");
const forSelf = ref(true);
const selectedEmployee = ref<Employee | null>(null);
const empSearch = ref("");
const type = ref("");
const motif = ref("");

const filteredEmployees = computed(() => {
  if (!empSearch.value) return EMPLOYEES.filter((e) => e.id !== CURRENT_USER_ID);
  return searchEmployees(empSearch.value).filter((e) => e.id !== CURRENT_USER_ID);
});

const reset = () => {
  mode.value = "choice";
  forSelf.value = true;
  selectedEmployee.value = null;
  empSearch.value = "";
  type.value = "";
  motif.value = "";
};

const handleClose = () => {
  reset();
  emit('update:open', false);
};

const handleSubmit = () => {
  const empId = forSelf.value ? CURRENT_USER_ID : selectedEmployee.value?.id;
  if (!empId || !type.value) return;
  emit('submit', empId, type.value, motif.value);
  handleClose();
};

const chooseMode = (self: boolean) => {
  forSelf.value = self;
  if (self) {
    selectedEmployee.value = getEmployee(CURRENT_USER_ID) || null;
  }
  mode.value = "form";
};

const getAvatar = () => {
  const e = forSelf.value ? getEmployee(CURRENT_USER_ID) : selectedEmployee.value;
  return e?.avatar || "?";
};

const getEmpName = () => {
  const e = forSelf.value ? getEmployee(CURRENT_USER_ID) : selectedEmployee.value;
  return e ? `${e.prenom} ${e.nom}` : "";
};

const getEmpPoste = () => {
  const e = forSelf.value ? getEmployee(CURRENT_USER_ID) : selectedEmployee.value;
  return e?.poste;
};

const getEmpDept = () => {
  const e = forSelf.value ? getEmployee(CURRENT_USER_ID) : selectedEmployee.value;
  return e?.departement;
};
</script>

<template>
  <Dialog :open="open" @update:open="(val) => { if (!val) handleClose(); else emit('update:open', true); }">
    <DialogContent class="sm:max-w-lg">
      <DialogHeader>
        <DialogTitle>Nouvelle Demande</DialogTitle>
      </DialogHeader>

      <div v-if="mode === 'choice'" class="grid grid-cols-2 gap-4 py-4">
        <button
          @click="chooseMode(true)"
          class="flex flex-col items-center gap-3 p-6 rounded-lg border-2 border-border hover:border-primary hover:bg-muted/50 transition-all"
        >
          <User class="h-8 w-8 text-primary" />
          <span class="font-medium">Pour moi</span>
        </button>
        <button
          @click="chooseMode(false)"
          class="flex flex-col items-center gap-3 p-6 rounded-lg border-2 border-border hover:border-primary hover:bg-muted/50 transition-all"
        >
          <Users class="h-8 w-8 text-primary" />
          <span class="font-medium">Pour un employé</span>
        </button>
      </div>

      <div v-else-if="mode === 'form'" class="space-y-4 py-2">
        <template v-if="!forSelf && !selectedEmployee">
          <div class="space-y-3">
            <div class="relative">
              <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Rechercher un employé..."
                v-model="empSearch"
                class="pl-9"
                autofocus
              />
            </div>
            <div class="max-h-48 overflow-y-auto rounded-lg border divide-y">
              <button
                v-for="emp in filteredEmployees"
                :key="emp.id"
                @click="selectedEmployee = emp"
                class="w-full flex items-center gap-3 p-3 hover:bg-muted/50 transition-colors text-left"
              >
                <EmployeeAvatar :initials="emp.avatar" size="sm" />
                <div>
                  <p class="text-sm font-medium">{{ emp.prenom }} {{ emp.nom }}</p>
                  <p class="text-xs text-muted-foreground">{{ emp.poste }}</p>
                </div>
              </button>
            </div>
          </div>
        </template>

        <template v-if="forSelf || selectedEmployee">
          <!-- Profile card -->
          <div class="flex items-center gap-4 p-4 rounded-lg bg-muted/50 border">
            <EmployeeAvatar :initials="getAvatar()" size="lg" />
            <div>
              <p class="font-semibold">{{ getEmpName() }}</p>
              <p class="text-sm text-muted-foreground">{{ getEmpPoste() }}</p>
              <p class="text-xs text-muted-foreground">{{ getEmpDept() }}</p>
            </div>
          </div>

          <div class="space-y-2">
            <label class="text-sm font-medium">Type d'attestation *</label>
            <Select :model-value="type" @update:model-value="(val) => type = String(val)">
              <SelectTrigger>
                <SelectValue placeholder="Sélectionner un type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="t in TYPES_ATTESTATION" :key="t" :value="t">{{ t }}</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div class="space-y-2">
            <label class="text-sm font-medium">Motif <span class="text-muted-foreground">(facultatif)</span></label>
            <Textarea
              placeholder="Précisez le motif de votre demande..."
              v-model="motif"
              :rows="3"
            />
          </div>

          <div class="flex justify-end gap-3 pt-2">
            <Button variant="outline" @click="handleClose">Annuler</Button>
            <Button @click="handleSubmit" :disabled="!type">Soumettre</Button>
          </div>
        </template>

        <div v-if="!forSelf && !selectedEmployee" class="flex justify-start">
          <Button variant="ghost" @click="mode = 'choice'">← Retour</Button>
        </div>
      </div>
    </DialogContent>
  </Dialog>
</template>
