// src/components/attestation/RejetModal.vue
<script setup lang="ts">
import { ref } from "vue";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

interface RejetModalProps {
  open: boolean;
  reference: string;
}

const props = defineProps<RejetModalProps>();
const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'confirm', motif: string): void;
}>();

const motif = ref("");

const handleConfirm = () => {
  if (!motif.value.trim()) return;
  emit('confirm', motif.value.trim());
  motif.value = "";
};

const handleClose = () => {
  motif.value = "";
  emit('update:open', false);
};
</script>

<template>
  <Dialog :open="open" @update:open="(val) => { if (!val) handleClose(); else emit('update:open', true); }">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>Rejeter la demande {{ reference }}</DialogTitle>
      </DialogHeader>
      <div class="space-y-4 py-2">
        <div class="space-y-2">
          <label class="text-sm font-medium">Motif du rejet <span class="text-destructive">*</span></label>
          <Textarea
            placeholder="Veuillez saisir le motif du rejet..."
            v-model="motif"
            :rows="4"
            autofocus
          />
        </div>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="handleClose">Annuler</Button>
          <Button variant="destructive" @click="handleConfirm" :disabled="!motif.trim()">
            Confirmer le rejet
          </Button>
        </div>
      </div>
    </DialogContent>
  </Dialog>
</template>

// src/components/attestation/RejetModal.tsx
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

interface RejetModalProps {
  open: boolean;
  onClose: () => void;
  onConfirm: (motif: string) => void;
  reference: string;
}

export function RejetModal({ open, onClose, onConfirm, reference }: RejetModalProps) {
  const [motif, setMotif] = useState("");

  const handleConfirm = () => {
    if (!motif.trim()) return;
    onConfirm(motif.trim());
    setMotif("");
  };

  const handleClose = () => {
    setMotif("");
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(o) => !o && handleClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Rejeter la demande {reference}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <div className="space-y-2">
            <label className="text-sm font-medium">Motif du rejet <span className="text-destructive">*</span></label>
            <Textarea
              placeholder="Veuillez saisir le motif du rejet..."
              value={motif}
              onChange={(e) => setMotif(e.target.value)}
              rows={4}
              autoFocus
            />
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" onClick={handleClose}>Annuler</Button>
            <Button variant="destructive" onClick={handleConfirm} disabled={!motif.trim()}>
              Confirmer le rejet
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
