// src/components/attestation/StatusBadge.tsx
import { cn } from "@/lib/utils";

const STATUS_MAP = {
  en_attente: { label: "En attente", class: "status-pending border" },
  validee: { label: "Validée", class: "status-approved border" },
  rejetee: { label: "Rejetée", class: "status-rejected border" },
} as const;

interface StatusBadgeProps {
  statut: keyof typeof STATUS_MAP;
}

export function StatusBadge({ statut }: StatusBadgeProps) {
  const config = STATUS_MAP[statut];
  return (
    <span className={cn("inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold", config.class)}>
      {config.label}
    </span>
  );
}

// src/components/attestation/StatusBadge.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { computed } from "vue";

const STATUS_MAP = {
  en_attente: { label: "En attente", class: "bg-[hsl(var(--status-pending-bg))] text-[hsl(var(--status-pending))] border-[hsl(var(--status-pending))/0.2]" },
  validee: { label: "Validée", class: "bg-[hsl(var(--status-approved-bg))] text-[hsl(var(--status-approved))] border-[hsl(var(--status-approved))/0.2]" },
  rejetee: { label: "Rejetée", class: "bg-[hsl(var(--status-rejected-bg))] text-[hsl(var(--status-rejected))] border-[hsl(var(--status-rejected))/0.2]" },
} as const;

interface StatusBadgeProps {
  statut: keyof typeof STATUS_MAP;
}

const props = defineProps<StatusBadgeProps>();

const config = computed(() => STATUS_MAP[props.statut]);
</script>

<template>
  <span :class="cn('inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold', config.class)">
    {{ config.label }}
  </span>
</template>
